import time
from pageObjects.Loginpage import LoginPage
from pageObjects.Homepage import HomePage
from pageObjects.ENGHC import ENGHC
from utilities.readProperties import ReadConfig


class TestENGHC:
    baseURL = ReadConfig.getApplicationURL()
    username = ReadConfig.getUseremail()
    password = ReadConfig.getPassword()

    def test_login(self, setup):
        self.driver = setup
        self.driver.get(self.baseURL)
        self.driver.maximize_window()

        # LoginPage
        self.lp = LoginPage(self.driver)
        self.lp.setUserName(self.username)
        self.lp.setPassword(self.password)
        self.lp.clickLogin()

        # HomePage Logbook
        self.hm = HomePage(self.driver)
        self.hm.Clicklogbook()

        #ENGHC
        self.engpage = ENGHC(self.driver)
        self.engpage.ClickQC()
        time.sleep(1.3)
        self.engpage.ClickEng()
        time.sleep(1.3)
        self.engpage.ClickHC()
        time.sleep(1.3)
        self.engpage.ClickAddnew()
        time.sleep(1.3)
        self.engpage.SetEquipName()
        time.sleep(1.3)
        self.engpage.SetEquipId()
        time.sleep(1.3)
        self.engpage.SetTOM()
        time.sleep(1.3)
        self.engpage.SetDesc("Corrupted")
        time.sleep(1.3)
        self.engpage.SetSU()
        time.sleep(1.3)
        self.engpage.SetTOB("16")
        time.sleep(1.3)
        self.engpage.SetSF()
        time.sleep(1.3)
        self.engpage.SetRemarks("History card added")
        time.sleep(1.3)
        self.engpage.Subbtn()
        time.sleep(1.3)
        self.engpage.esigusername("UF001")
        time.sleep(1.3)
        self.engpage.esigpassword("syn1234")
        time.sleep(1.3)
        self.engpage.esigsave()
        time.sleep(1.3)
        self.engpage.scroll()
        time.sleep(1.3)
        self.engpage.clickgrid()
        time.sleep(1.3)
        self.engpage.SubReview()
        time.sleep(1.3)
        self.engpage.esigusername("UF001")
        time.sleep(1.3)
        self.engpage.esigpassword("syn1234")
        time.sleep(1.3)
        self.engpage.esigsave()
        time.sleep(1.3)
        self.engpage.scroll()
        time.sleep(1.3)
        self.engpage.clickgrid()
        time.sleep(1.3)
        self.engpage.activitylog()
        time.sleep(1.3)
        self.engpage.backbtn()
        time.sleep(1.3)
        self.engpage.clickPlusIcon()
        time.sleep(1.3)
        self.engpage.fromdate()
        time.sleep(1.3)
        self.engpage.calendarfromdate()
        time.sleep(1.3)
        self.engpage.todate()
        time.sleep(1.3)
        self.engpage.calendartodate()
        time.sleep(1.3)
        self.engpage.calendarsearch()
        time.sleep(1.3)
        self.engpage.calendersearchref()
        time.sleep(1.3)
        self.engpage.sort_asc()
        time.sleep(1.3)
        self.engpage.sort_desc()
        time.sleep(1.3)
        self.engpage.show_entries()
        time.sleep(1.3)
        self.engpage.exportbtn()
        time.sleep(1.3)
        self.engpage.scrollnext()
        time.sleep(1.3)
        self.engpage.scrollprev()
        time.sleep(1.3)
        self.engpage.dynamicfltr("WN/EL/0036")
        time.sleep(3)
        self.driver.close()
        assert True
